config/routes.rb
Rails.application.routes.draw do
  get 'relationships/index'

  resources :dependents
  resources :relationships
  
  devise_for :users, controllers: { :sessions => "users/sessions", :passwords => 'users/passwords', :registrations => 'users/registrations' }

  get "users/" => "users/generic#new", as: "all_users"
  get "/dashboard/:id" => "dashboards#index", as: "v_edit_users"
  get "/dashboard" => "dashboards#new", as: "v_new_users"
  post "/dashboard" => "dashboards#create", as: "new_users"
  patch "/dashboard" => "dashboards#update", as: "c_edit_users"
  
  # get 'users/', to: 'users/registrations#index', as: 'index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboards#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :user_departments, dependent: :destroy
  has_many :users, through: :user_departments
end

app/models/dependent.rb
class Dependent < ApplicationRecord
  has_many :user_dependents, dependent: :destroy
  has_many :users, through: :user_dependents
  belongs_to :relationship
end

app/models/image.rb
class Image < ApplicationRecord
  # include ImageUploader::Attachment(:image) 
  belongs_to :imageable, polymorphic: true
  has_one_attached :image_data
  # before_create :set_image_filename

  # private

  # def set_image_filename
  #   extension = File.extname(image_file_name).downcase
  #   self.image_file_name = "#{SecureRandom.hex(8)}#{extension}"
  # end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_many :dependents
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles, dependent: :destroy
  has_many :users, :through => :user_roles
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :user_teams, dependent: :destroy
  has_many :users, :through => :user_teams
  # accepts_nested_attributes_for :user_teams
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  belongs_to :company

  has_many :images, as: :imageable, dependent: :destroy

  has_many :user_teams, dependent: :destroy
  has_many :teams, :through => :user_teams
  has_many :user_departments, dependent: :destroy
  has_many :departments, :through => :user_departments
  has_many :user_roles, dependent: :destroy
  has_many :roles, :through => :user_roles
  has_many :user_dependents, dependent: :destroy
  has_many :dependents, :through => :user_dependents

  # accepts_nested_attributes_for :teams
  accepts_nested_attributes_for :user_teams, allow_destroy: true
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :user_departments, allow_destroy: true
  accepts_nested_attributes_for :dependents, allow_destroy: true
  accepts_nested_attributes_for :user_roles, allow_destroy: true

  # Validations
  validates :email, presence: true, uniqueness: {:case_sensitive => false}
  validates :gender, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  # Self Methods 
  def age
    return nil if date_of_birth.nil?
    return 0 if Date.today < date_of_birth 
    days_in_a_year = 365
    now = Time.current.to_date
    diff = (now - date_of_birth)
    (diff / days_in_a_year).floor
  end

  # Enums Declaration
  enum gender: [:male, :female]

  # Scopes
  scope :males, -> { where(:gender => 0)}
  scope :females, -> { where(:gender => 1)}

  scope :teams, ->(status = nil) { status.nil? == true ? joins(:teams) : joins(:teams).where(:user_teams => {:is_active => status}) }
  
  scope :select_all, ->(status = nil) { teams(status).select("users.id,users.first_name,users.last_name,users.email,users.gender,users.date_of_birth,teams.id as team_id,teams.name as team_name").distinct }

end

app/models/user_department.rb
class UserDepartment < ApplicationRecord
  belongs_to :user
  belongs_to :department
end

app/models/user_dependent.rb
class UserDependent < ApplicationRecord
  belongs_to :user
  belongs_to :dependent
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/user_team.rb
class UserTeam < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:id])
    @data = {:user => @user}
  end

  def new
    @user = User.new
    @data = {:user => @user}
    @user.images.build

    @find = User.last
  end


  def update 
    debugger
  end

  def create
    x = User.new(user_params)
    debugger
    x.save
  end

  private
  def user_params 
    params.require(:user).permit(:first_name, :last_name,:email, :password, :password_confirmation, :gender, :date_of_birth, :company_id, user_teams_attributes: [:id, :team_id, :_destroy], user_roles_attributes: [:id, :role_id, :_destroy], dependents_attributes: [:id, :name, :gender, :relationship_id], images_attributes: [:id, :is_active, :_destroy, :image_data])
  end
end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  def index
    @dependents = Dependent.all
    render json: @dependents
  end

  def create
    debugger
  end

  def new
    debugger
    @dependent = Dependent.new
  end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "react"

  def index
    users = User.all
    @data = {:users => users}
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def index
    @relations = Relationship.all
    render json: @relations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/dashboards/_departments.html.erb
<div class="mb-3 pb-5 pt-5">
<% Department.all.each do |department| %>
    <% assigned = user.departments.include?(department) %>
     <%= f.fields_for :user_departments, assigned ? user.user_departments.find_by(department_id: department.id) : UserDepartment.new do |department_fields| %>
      <%= department_fields.check_box :department_id, {}, department.id, nil %>
      <%= department_fields.label :department_id, department.name, class: "form-check-label" %>
    <% end %>
    <br/>
  <% end %>
</div>

app/views/dashboards/_dependents.html.erb
<%= react_component("Dependents", props: {user: user, dependents: user.dependents}, prerender: false) %>

app/views/dashboards/_images.html.erb
  <%= f.fields_for :images do |image_fields| %>
     <%= image_fields.label :image_data %>
    <%= image_fields.file_field :image_data %>
    <%#= image_fields.text_field :image_data%>
    <%= image_fields.label :is_active %>
    <%= image_fields.check_box :is_active %>
  <% end %>

app/views/dashboards/_roles.html.erb
<div class="mb-3 pb-5 pt-5">
<% Role.all.each do |role| %>
    <% assigned = user.roles.include?(role) %>
     <%= f.fields_for :user_roles, assigned ? user.user_roles.find_by(role_id: role.id) : UserRole.new do |role_fields| %>
      <%= role_fields.check_box :role_id, {}, role.id, nil %>
      <%= role_fields.label :role_id, role.name, class: "form-check-label" %>
    <% end %>
    <br/>
  <% end %>
</div>

app/views/dashboards/_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item" data-tab="tab1" data-toggle="tab" onclick="activaTab(this)">
    <a class="nav-link active" href="#tab1" data-toggle="tab">Basic Information</a>
  </li>
  <li class="nav-item" data-tab="tab2" data-toggle="tab" onclick="activaTab(this)">
    <a class="nav-link" href="#tab2" data-toggle="tab">Roles</a>
  </li>
  <li class="nav-item" data-tab="tab3"  data-toggle="tab"onclick="activaTab(this)">
    <a class="nav-link" href="#tab3" data-toggle="tab">Teams</a>
  </li>
  <li class="nav-item" data-tab="tab4"  data-toggle="tab"onclick="activaTab(this)">
    <a class="nav-link" href="#tab4" data-toggle="tab">Insurance Card Details</a>
  </li>
  <li class="nav-item" data-tab="tab5"  data-toggle="tab"onclick="activaTab(this)">
    <a class="nav-link" href="#tab5" data-toggle="tab">Departments</a>
  </li>
  <li class="nav-item" data-tab="tab6"  data-toggle="tab"onclick="activaTab(this)">
    <a class="nav-link" href="#tab6" data-toggle="tab">Upload Image</a>
  </li>
</ul>

<div class="tab-content">
  <div id="tab1" class="container tab-pane active">

    <%= render partial: 'users', locals: {f: f, user: user } %>
  </div>
  <div id="tab2" class="container tab-pane">

    <%= render partial: 'roles', locals: {f: f, user: user } %>
  </div>
  <div id="tab3" class="container tab-pane">
    <%= render partial: 'teams', locals: {f: f, user: user } %>
  </div>
  <div id="tab4" class="container tab-pane">
    <%= render partial: 'dependents', locals: {f: f, user: user } %>
  </div>
  <div id="tab5" class="container tab-pane">
    <%= render partial: 'departments', locals: {f: f, user: user } %>
  </div>
  <div id="tab6" class="container tab-pane">
    <%= render partial: 'images', locals: {f: f, user: user } %>
  </div>
</div>

app/views/dashboards/_teams.html.erb
<div class="mb-3 pt-5 pb-5">
<% Team.all.each do |team| %>
  <% assigned = user.teams.include?(team) %>
  
    <%= f.fields_for :user_teams, assigned ? user.user_teams.find_by(team_id: team.id) : UserTeam.new do |team_fields| %>
    <%= react_component("Teams", props: {id: team.id, name: team.name}, prerender: false) %>
  <% end %>
  <br/>
<% end %>

</div>

app/views/dashboards/_users.html.erb
<div class="row pt-3">
  <div class="col mb-3">
    <%= f.label :first_name, class: "form-label" %>
    <%= f.text_field :first_name, value: "Ahmad", class: "form-control" %>
  </div>
  <div class="col mb-3">
    <%= f.label :last_name, class: "form-label" %>
    <%= f.text_field :last_name , value: "raza", class: "form-control" %>
  </div>
  <div class="col mb-3">
    <%= f.label :company_id, class: "form-label" %>
    <%= f.text_field :company_id , value: "1", class: "form-control" %>
  </div>
</div>
<div class="row">
  <div class="col mb-3">
    <%= f.label :gender, class: "form-label" %>
    <%= f.text_field :gender, value: "male", class: "form-control" %>
  </div>
  <div class="col mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.text_field :email, value: "male", class: "form-control" %>
  </div>
  <div class="col mb-3"></div>
</div>
<div class="row">
  <div class="col mb-3">
    <%= f.label :password_confirmation, class: "form-label" %>
    <%= f.text_field :password_confirmation, value: "123456", class: "form-control" %>
  </div>
  <div class="col mb-3">
    <%= f.label :password, class: "form-label" %>
    <%= f.text_field :password, value: "123456", class: "form-control" %>
  </div>
  <div class="col mb-3"></div>
</div>

app/views/dashboards/index.html.erb
<h1>Welcome</h1>

<%= link_to "All Users", all_users_path %>
<%= form_for @user, url: "#", remote: true do |f| %>
<%= render partial: 'tabs', locals: {f: f, user: @user } %>
<%
=begin%>
 <%= f.submit %> 
<%
=end%>
  
  <button id="save-record">Save</button>
<% end %>

<script>


function activaTab(e){
  const tab = e.dataset ? e.dataset.tab : e
  window.jQuery('.nav-tabs a[href="#' + tab + '"]').tab('show');
};


window.addEventListener("load",function(){  

 const $ = window.jQuery
 activaTab(window.location.hash.replace("#",""))
  $("#save-record").on('click', function(e) {

    const token = 
      document.querySelector('[name=csrf-token]').content
  
    e.preventDefault();
    var form = $("#new_user");
    var url = form.attr('action');
    var method = form.attr('method');
    var data = form.serialize();

 $.ajax({
      url: "<%= c_edit_users_path %>",
      method: method,
      data: data,
      headers: {
        "X-CSRF-TOKEN": token,
      },
      dataType: 'json',
      success: function(response) {
        console.log("success",response)
      },
      error: function(xhr, status, error) {
        console.log("error",xhr,status,error)
      }
    }); 
    
  }); 

})

</script>

app/views/dashboards/new.html.erb
<h1>Welcome</h1>


<%= link_to "All Users", all_users_path %>
<%= form_for @user, url: "#", remote: true do |f| %>
<%= render partial: 'tabs', locals: {f: f, user: @user } %>
    <button id="save-record">Save</button>
<% end %>
<%= @user %>
<%= image_tag url_for(@find.images.last.image_data) %>


<script>


function activaTab(e){
  const tab = e.dataset ? e.dataset.tab : e

  window.jQuery('.nav-tabs a[href="#' + tab + '"]').tab('show');
};


window.addEventListener("load",function(){
  activaTab(window.location.hash.replace("#",""))  
 const $ = window.jQuery
 const token = document.querySelector('[name=csrf-token]').content
  $("#save-record").on('click', function(e) {
    e.preventDefault();
    var form = $("#new_user");
    var url = form.attr('action');
    var method = form.attr('method');
    const file = $("#user_images_attributes_0_image_data")[0]
    var attachment = file.files[0];
    var data = new FormData(form[0])//form.serialize();

//    for (var [key, value] of data.entries()) { 
  //    if(typeof value != 'string'){
    //    console.log(key, value[0], typeof value);
//      }
  //    console.log(key, value, typeof value);
    //}
    
   window.axios.post("<%= new_users_path %>",data,{ headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')} }).then((r)=>{
      console.log(r)
    })
   
/*
 $.ajax({
      url: "<%= new_users_path %>",
      method: method,
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      data: data,
      //dataType: 'json',
      success: function(response) {
        console.log("success",response)
      },
      error: function(xhr, status, error) {
        console.log("error",xhr,status,error)
      }
    }); 
  */
  }); 
})

</script>